# Generated by Django 5.1.6 on 2025-03-18 21:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0004_wilaya_alter_personnel_grade_personnel_wilaya'),
    ]

    operations = [
        migrations.CreateModel(
            name='WilayaDistance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField()),
                ('wilaya_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_wilaya', to='personnel.wilaya')),
                ('wilaya_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_wilaya', to='personnel.wilaya')),
            ],
            options={
                'unique_together': {('wilaya_from', 'wilaya_to')},
            },
        ),
    ]
