# Generated by Django 5.1.6 on 2025-03-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personnel', '0004_wilaya_alter_personnel_grade_personnel_wilaya'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_payment_north', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_payment_south', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lodging_payment_north', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lodging_payment_south', models.DecimalField(decimal_places=2, max_digits=10)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.grade')),
            ],
        ),
    ]
