# Generated by Django 5.1.6 on 2025-03-19 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0001_initial'),
        ('personnel', '0004_wilaya_alter_personnel_grade_personnel_wilaya'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_arrival', models.DateField()),
                ('date_departure', models.DateField()),
                ('transport_type', models.CharField(choices=[('Personal Car', 'Voiture personnelle'), ('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Faculty Driver', 'Chauffeur de la faculté')], max_length=50)),
                ('time_departure', models.TimeField()),
                ('time_arrival', models.TimeField()),
                ('funding_type', models.CharField(choices=[('100% Funded', '100% financé'), ('25% Funding', '25% financé')], max_length=30)),
                ('mission_nature', models.CharField(choices=[('Thesis Discussion', 'Soutenance de thèse'), ('Forum', 'Forum'), ('Administrative Task', 'Tâche administrative'), ('Other', 'Autre')], max_length=50)),
                ('destination_wilaya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.wilaya')),
            ],
        ),
        migrations.CreateModel(
            name='MissionPersonnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meal_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lodging_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='missions.mission')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.personnel')),
            ],
        ),
    ]
