# Generated by Django 5.1.6 on 2025-03-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0002_mission_missionpersonnel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='transport_type',
            field=models.CharField(choices=[('Personal Car', 'Voiture personnelle'), ('Bus', 'Bus'), ('Taxi', 'Taxi'), ('Faculty Driver', 'Chauffeur de la faculté'), ('other', 'autre')], max_length=50),
        ),
    ]
