# Generated by Django 5.1.6 on 2025-05-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0003_alter_mission_transport_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionpersonnel',
            name='meal_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='missionpersonnel',
            name='transport_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
