# Generated by Django 5.1.6 on 2025-05-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0004_alter_missionpersonnel_meal_payment_and_more'),
        ('personnel', '0007_personnel_year'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='missionpersonnel',
            unique_together={('personnel', 'mission')},
        ),
    ]
