# Generated by Django 5.1.6 on 2025-05-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0005_alter_missionpersonnel_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradepayment',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='mission',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='missionpersonnel',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
