# Generated by Django 5.1.6 on 2025-05-22 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0006_gradepayment_year_mission_year_missionpersonnel_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('added_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
