# Generated by Django 5.1.6 on 2025-05-23 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missions', '0007_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
