# Generated by Django 5.1.6 on 2025-03-05 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('profession', models.CharField(choices=[('Worker', 'Worker'), ('Teacher', 'Teacher'), ('Faculty Driver', 'Faculty Driver')], max_length=50)),
                ('grade', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=50, unique=True)),
                ('is_ccp_account', models.BooleanField(default=False)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=20)),
            ],
        ),
    ]
