# Generated by Django 5.1.6 on 2025-03-05 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(choices=[('Teacher', 'Teacher'), ('Worker', 'Worker'), ('Driver', 'Driver')], max_length=20)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='city',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='state',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='street',
        ),
        migrations.RemoveField(
            model_name='personnel',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='personnel',
            name='address',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='account_number',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='profession',
            field=models.CharField(choices=[('Teacher', 'Teacher'), ('Worker', 'Worker'), ('Driver', 'Driver')], max_length=20),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='personnel.grade'),
        ),
    ]
