# Generated by Django 5.1.6 on 2025-03-05 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0002_grade_remove_personnel_city_remove_personnel_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personnel',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='personnel.grade'),
        ),
    ]
