# Generated by Django 5.1.6 on 2025-03-18 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0003_alter_personnel_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wilaya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='personnel',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personnel.grade'),
        ),
        migrations.AddField(
            model_name='personnel',
            name='wilaya',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='personnel.wilaya'),
        ),
    ]
