# Generated by Django 5.1.6 on 2025-03-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0004_wilaya_alter_personnel_grade_personnel_wilaya'),
    ]

    operations = [
        migrations.AddField(
            model_name='wilaya',
            name='ar_name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='code',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='is_south',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wilaya',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
