# Generated by Django 5.1.6 on 2025-05-19 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0005_wilaya_ar_name_wilaya_code_wilaya_is_south_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wilaya',
            name='ar_name',
        ),
        migrations.RemoveField(
            model_name='wilaya',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='wilaya',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='code',
            field=models.PositiveIntegerField(default='00', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='wilaya',
            name='is_south',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
