# Generated by Django 5.1.6 on 2025-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0006_remove_wilaya_ar_name_remove_wilaya_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='year',
            field=models.PositiveIntegerField(default=2025),
        ),
    ]
